name: Test all DS challenges

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test_target:
          - test-1
          - test-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.10

      - name: Run one test target
        id: maelstromTest
        run: |
          echo "Running make ${{ matrix.test_target }}"
          make "${{ matrix.test_target }}"

      - name: Upload store folder
        uses: actions/upload-artifact@v3
        if: success() || (failure() && steps.maelstromTest.outcome == 'failure')
        with:
          name: store-${{ matrix.test_target }}
          path: |
            store/
            !./**/current
            !./**/latest