name: Test all DS challenges

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test_target:
          - test-1
          - test-2
          - test-3a
          - test-3b
          - test-3c
          - test-3d

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install APT dependencies
        run: sudo apt install -y graphviz gnuplot xvfb

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.10
          cache-dependency-path: 1_echo/go.sum

      - name: Run one test target
        id: maelstromTest
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          echo "Running make ${{ matrix.test_target }}"
          make "${{ matrix.test_target }}"

      - name: Upload store folder
        uses: actions/upload-artifact@v4
        if: success() || (failure() && steps.maelstromTest.outcome == 'failure')
        with:
          name: store-${{ matrix.test_target }}
          path: |
            store/
            !./**/current
            !./**/latest